---
- name: keepalived | Deploy keepalived configuration
  template:
    src: "keepalived.j2"
    dest: "{{ hostvars[inventory_hostname]['keepalived_destination'] + '/' +
      'keepalived.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "keepalived -lt -f %s"
  notify:
  - "Restart keepalived"
- name: keepalived | Enable keepalived service
  service:
    name: "{{ hostvars[inventory_hostname]['keepalived_service'] }}"
    state: "started"
    enabled: "yes"
  when:
  - "hostvars[inventory_hostname]['keepalived_enable'] is defined"
  - "hostvars[inventory_hostname]['keepalived_enable'] == 'true'"
