---
- name: "keepalived | Deploy keepalived configuration"
  ansible.builtin.template:
    src: "keepalived.j2"
    dest: "{{ lookup('ansible.builtin.vars', 'keepalived_destination') +
      '/keepalived.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "keepalived -t -f %s"
  notify:
    - "Restart keepalived"
- name: "keepalived | Enable keepalived service"
  ansible.builtin.systemd:
    name: "{{ lookup('ansible.builtin.vars', 'keepalived_service') }}"
    enabled: "yes"
  when:
    - "lookup('ansible.builtin.vars', 'keepalived', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'keepalived') |
       community.general.json_query(lookup('ansible.builtin.vars',
      'keepalived_enable', default='')) == 'true'"
  vars:
    keepalived_enable: "[] | map(&enable || 'false', @) | [0]"
