---
- name: keepalived | Make work dir
  file:
    path: "{{ hostvars[inventory_hostname]['keepalived_destination'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "755"
- name: keepalived | Generate keepalived configuration
  template:
    src: "keepalived.j2"
    dest: "{{ hostvars[inventory_hostname]['keepalived_destination'] + '/' + 'keepalived.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
  - "Enable keepalived"
  - "Start keepalived"
