---
- import_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "hostvars[inventory_hostname]['keepalived_install_package'] is defined"
  - "hostvars[inventory_hostname]['keepalived_install_package'] == 'true'"
- include_tasks: deploy_keepalived.yml
  when:
  - "hostvars[inventory_hostname]['keepalived'] is defined"
  - "hostvars[inventory_hostname]['keepalived'] != ''"
