---
- name: "keepalived | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "keepalived | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['keepalived'] is defined"
    - "hostvars[inventory_hostname]['keepalived'] != ''"
    - "hostvars[inventory_hostname]['keepalived'] |
       json_query(vars['keepalived_install_package']) is defined"
    - "hostvars[inventory_hostname]['keepalived'] |
       json_query(vars['keepalived_install_package']) == 'true'"
  vars:
    keepalived_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "keepalived | Include deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy_keepalived.yml"
  when:
    - "hostvars[inventory_hostname]['keepalived'] is defined"
    - "hostvars[inventory_hostname]['keepalived'] != ''"
