---
- include: pre_requisite.yml
- include: packages.yml
  when:
  - "hostvars[inventory_hostname]['keepalived_install_package'] is defined"
  - "hostvars[inventory_hostname]['keepalived_install_package'] == 'true'"
- include: deploy_keepalived.yml
  when:
  - "hostvars[inventory_hostname]['keepalived'] is defined"
  - "hostvars[inventory_hostname]['keepalived'] != ''"
