---
- name: keepalived | Add the OS specific variables
  include_vars: "{{
    hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: keepalived | Make work dir
  file:
    path: "{{ hostvars[inventory_hostname]['keepalived_destination'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "755"
