---
- name: Restart keepalived
  service:
    name: "{{ hostvars[inventory_hostname]['keepalived_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['keepalived_restart'] is defined"
  - "hostvars[inventory_hostname]['keepalived_restart'] == 'true'"
