---
- name: Restart keepalived
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['keepalived_service'] }}"
    state: "{{ vars['keepalived_restart_cmd'] }}"
  when:
    - "hostvars[inventory_hostname]['keepalived'] is defined"
    - "hostvars[inventory_hostname]['keepalived'] != ''"
    - "hostvars[inventory_hostname]['keepalived'] |
       json_query(vars['keepalived_restart']) is defined"
    - "hostvars[inventory_hostname]['keepalived'] |
       json_query(vars['keepalived_restart']) == 'true'"
  vars:
    keepalived_restart: "[] | map(&restart || 'false', @) | [0]"
